---
kind: pipeline
type: kubernetes
name: test

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn
- name: docker  
  image: docker
  commands:
    - docker build -t harbor:443/tmp/foo .
    - docker push harbor:443/tmp/foo
