---
kind: pipeline
type: docker
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn
