---
kind: pipeline
type: kubernetes
name: aviary-frontend


clone:
  skip_verify: true 

  
steps:
- name: kaniko  
  image: harness/kaniko
  settings:
    username: robot$drone
    password: bmVoduOjEqaaxZAb87AXqAc29ORcik2v
    registry: harbor.local:443
    repo: harbor.local:443/aviary-frontend/aviary-frontend
    tags: latest
    skip_tls_verify: true

  volumes:
  - name: ca-certificates.crt
    path: /drone/src/ca.crt

volumes:
  - name: ca-certificates.crt
    host:
      path: /etc/ssl/certs
