---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
- name: kaniko  
  image: plugins/kaniko
  settings:
    username: robot$tmp+drone 
    password: 0c2GUJcQ3ciIWuQFS2Fzgsge1Sv75kic
    repo: harbor:443/tmp/foo
    skip_tls_verify: true
    tags:
    - latest
  volumes: 
  - name: ca.crt
    path: ~/.docker

volumes:
  - name: ca.crt
    configMap:
      name: ca-certs

