---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn
- name: kaniko  
  image: plugins/kaniko
  settings:
    username: robot$drone
    password: to0EaYegAenDX2KRI0cQKGfkNOuXD9kt
    repo: harbor:443/tmp/foo
    tags:
    - latest
  volumes:
  - name: certs
    path: /etc/ssl/certs

volumes:
  - name: certs
    host:
      path: /etc/ssl/certs/ca-certificates.crt
