kind: pipeline
name: default
namespace: drone

steps:
- name: clone
  image: debian
  settings:
    skip_verify: true
---
kind: pipeline
type: kubernetes
name: test

steps:
- name: pwd
  image: debian
  commands:
  - pwd
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn
- name: docker  
  image: plugins/docker
  settings:
    username: robot$drone
    password: to0EaYegAenDX2KRI0cQKGfkNOuXD9kt
    repo: harbor:443/tmp/foo
    tags:
    - latest
