---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
- name: kaniko  
  image: plugins/kaniko
  settings:
    username: robot$drone
    password: to0EaYegAenDX2KRI0cQKGfkNOuXD9kt
    repo: harbor:443/tmp/foo
    build_args: --tlsverify=false
    tags:
    - latest
  volumes: 
  - name: certs
    path: ~/.docker

volumes:
  - name: ca.crt
    configMap:
      name: ca-certs

