kind: pipeline
type: kubernetes
name: test
namespace: drone

steps:
- name: pwd
  image: debian
  commands:
  - pwd
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn
- name: docker  
  image: plugins/docker
  settings:
    username: bmath
    password: none
    repo: harbor:443/tmp/foo
    tags:
    - latest