kind: pipeline
type: kubernetes
name: test
namespace: drone

steps:
- name: pwd
  image: debian
  commands:
  - pwd
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn

  
