---
kind: pipeline
type: kubernetes
name: aviary-frontend


clone:
  skip_verify: true 

  
steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls




- name: kaniko  
  image: harness/kaniko
  settings:
    username: robot$drone
    password: 7D3UfzootZU8mS0acitPro0ni5EXcSGk
    registry: harbor.local:443
    repo: harbor.local:443/aviary-frontend/aviary-frontend
    tags: latest
    skip_tls_verify: true

  volumes:
  - name: ca-certificates.crt
    path: /drone/src/ca.crt

volumes:
  - name: ca-certificates.crt
    host:
      path: /etc/ssl/certs
