---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
- name: kaniko  
  image: plugins/kaniko:1.10.4
  settings:
    privileged: true
    username: drone 
    password: Drone1111
    repo: harbor:443/tmp/foo
    skip_tls_verify: true
    tags:
    - latest
  volumes: 
  - name: config.json
    path: /kaniko/.docker
volumes:
  - name: config.json
    secret:
      name: kaniko-secret
