---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
- name: kaniko  
  image: harness/kaniko
  settings:
    username: drone 
    password: Drone1111
    registry: harbor:443
    repo: harbor:443/tmp/aviary-frontend
    tags: drone
    skip_tls_verify: true

  volumes:
  - name: ca-certificates.crt
    path: /drone/src/ca.crt

volumes:
  - name: ca-certificates.crt
    host:
      path: /etc/ssl/certs
