---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
- name: kaniko  
  image: harness/kaniko
  settings:
    username: drone 
    password: Drone1111
    repo: harbor:443/tmp/foo
    skip_tls_verify: true
  