---
kind: pipeline
type: kubernetes
name: aviary-frontend

clone:
  skip_verify: true

steps:
- name: pwd
  image: debian
  commands:
  - pwd
  - ls
- name: build
  image: debian
  commands:
  - apt update
  - apt -y install python3-bottle gunicorn
- name: contain
  image: docker
  commands:
    - docker build -t foo .
    - docker tag foo harbor:443/tmp/foo
    - docker push haarbor:443/tmp/foo